name: Build session MP3s

on:
  push:
    branches: [ main ]
    paths:
      - "index.html"
      - ".github/workflows/tts-build.yml"
      - "tools/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-audio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # nodig om te kunnen pushen

      - name: Install deps (ffmpeg, espeak-ng, python)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg espeak-ng python3

      - name: Generate MP3s
        run: |
          mkdir -p audio
          python3 tools/tts_build.py

      - name: Re-encode MP3s to iOS/Safari-safe CBR
        shell: bash
        run: |
          shopt -s nullglob
          for f in audio/*.mp3; do
            echo "Fixing $f"
            ffmpeg -y -hide_banner -loglevel error -i "$f" \
              -ar 44100 \              # 44.1 kHz sample rate
              -ac 1 \                  # mono (voice)
              -codec:a libmp3lame \
              -b:a 128k \              # CBR 128 kbps
              -write_xing 0 \          # geen VBR/Xing header
              -map_metadata -1 \       # strip metadata
              "$f.tmp"
            mv "$f.tmp" "$f"
          done

      - name: Commit audio files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A audio/
          if git diff --cached --quiet; then
            echo "Geen wijzigingen om te committen"
          else
            git commit -m "Build MP3s (CBR 44.1kHz mono)"
            git push
          fi
